// Generated by CoffeeScript 1.7.1
(function() {
  var assert, request;

  assert = require('assert');

  request = require('supertest');

  describe('Account', function() {
    return describe('Account Provisioning', function() {
      return it('should create admin user', function() {
        return assert.ok(true);
      });
    });
  });

}).call(this);
