// Generated by CoffeeScript 1.7.1
(function() {
  var AccountController;

  AccountController = {
    view: function(req, res) {
      Account.find().exec((function(_this) {
        return function(err, accounts) {
          _this.viewResponse = '';
          if (err != null) {
            return _this.viewResponse = 'Sorry, error occurred: ' + err;
          } else {
            return accounts.forEach(function(account) {
              return _this.viewResponse += account.name + '<br />';
            });
          }
        };
      })(this));
      return res.send(this.viewResponse);
    },
    provision: function(req, res) {
      if ((req.body.email == null) || (req.body.user_name == null) || (req.body.name == null)) {
        return res.send('Required information is missing', 422);
      } else {
        return Account.findOneByName(req.body.name, function(err, account) {
          if (err != null) {
            throw err;
          }
          if (account != null) {
            return res.send({
              message: 'Account with this name already exists, please select different name.'
            }, 400);
          } else {
            return Account.create({
              name: req.body.name
            }, function(err, account) {
              if (err != null) {
                throw err;
              }
              return User.create({
                account: account,
                is_admin: true,
                email: req.body.email,
                name: req.body.name
              }, function(err, user) {
                if (err != null) {
                  throw err;
                }
                return res.send({
                  token: '-top-secret-token-'
                }, 200);
              });
            });
          }
        });
      }
    }
  };

  module.exports = AccountController;

}).call(this);
