// Generated by CoffeeScript 1.7.1
(function() {
  var ProjectContoller;

  ProjectContoller = {
    view: function(req, res) {
      return res.send('<h1>This is served from Coffee</h1>');
    }
  };

  module.exports = ProjectContoller;

}).call(this);
