// Generated by CoffeeScript 1.7.1
(function() {
  var Account;

  Account = {
    attributes: {
      name: {
        type: 'string',
        required: true,
        unique: true
      }
    }
  };

  module.exports = Account;

}).call(this);
